project_id = "ddxthibctyfplcrzwdve"

[api]
enabled = true

[db]
major_version = 15

[functions.admin-create-user]
verify_jwt = true

[functions.kcb-stk-push]
verify_jwt = false

[functions.kcb-ipn-notification]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.mpesa-status]
verify_jwt = false
