project_id = "ddxthibctyfplcrzwdve"

[api]
enabled = true

[db]
major_version = 17

[db.pooler]
default_pool_size = 15
max_client_conn = 200

[functions.admin-create-user]
verify_jwt = true

[functions.kcb-stk-push]
verify_jwt = false

[functions.kcb-ipn-notification]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.mpesa-status]
verify_jwt = false

[auth]
additional_redirect_urls = [
  "https://v0.app/chat/api/supabase/redirect/H1IS9PGwLlp",
  "https://jimwas-yn.vercel.app",
  "https://jimwas-yn.vercel.app/**",
  "https://vercel-yn.vercel.app",
  "https://vercel-yn.vercel.app/**",
  "http://localhost:5173",
  "http://localhost:5173/**",
  "https://jimwas-pos-27-mutiecharles777-2192s-projects.vercel.app/",
  "https://jimwas-pos-27-mutiecharles777-2192s-projects.vercel.app/**",
  "https://jimwas-*-pos-27-mutiecharles777-2192s-projects.vercel.app",
  "https://jimwas-*-pos-27-mutiecharles777-2192s-projects.vercel.app/**",
  "https://jimwas-pos-26-mutiecharles777-2192s-projects.vercel.app/",
  "https://jimwas-pos-26-mutiecharles777-2192s-projects.vercel.app/**",
  "https://jimwas-*-pos-26-mutiecharles777-2192s-projects.vercel.app",
  "https://jimwas-*-pos-26-mutiecharles777-2192s-projects.vercel.app/**"
]
site_url = "https://jimwas-yn.vercel.app"

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[storage.analytics]
enabled = true
max_namespaces = 10

[storage.image_transformation]
enabled = true
