import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowDownRight, ArrowUpRight, Calendar, ChevronDown, Download, FileText, Package, RefreshCw, Search, ShoppingBag, Truck, UserRound, Users, WalletCards, X } from 'lucide-react';
import { loadReportData, currency, inRange, shortId, type ReportData, type ReportKind } from '../lib/reporting';
import type { Product, Transaction } from '../lib/types';
import { AugustSalesReportView } from './AugustSalesReportView';

const REPORTS: Array<{ id: ReportKind; label: string; description: string; icon: typeof ShoppingBag }> = [
  { id: 'sales', label: 'Sales', description: 'Revenue, baskets, payment mix and transaction detail', icon: ShoppingBag },
  { id: 'financial', label: 'Financial', description: 'Paid, outstanding, tax, refunds and margin signals', icon: WalletCards },
  { id: 'inventory', label: 'Inventory', description: 'Stock valuation, movement and reorder risk', icon: Package },
  { id: 'delivery', label: 'Delivery', description: 'Fulfillment pipeline and COD exposure', icon: Truck },
  { id: 'customer', label: 'Customer', description: 'Customer value, loyalty and repeat activity', icon: Users },
  { id: 'user', label: 'User', description: 'Cashier activity and operational ownership', icon: UserRound },
  { id: 'august-sales', label: 'August 2026 EOD', description: 'Authoritative 31-day reconciliation, weekly rollups, & audit checkpoint', icon: Calendar },
];

function Metric({ label, value, detail, tone = 'emerald', trend }: { label: string; value: string; detail: string; tone?: 'emerald' | 'amber' | 'blue' | 'rose'; trend?: 'up' | 'down' }) {
  return <div className="rounded-xl border border-slate-700 bg-slate-800/80 p-4">
    <div className="flex items-start justify-between gap-3"><p className="text-xs font-medium uppercase tracking-[0.14em] text-slate-400">{label}</p>{trend && (trend === 'up' ? <ArrowUpRight size={17} className="text-emerald-400" /> : <ArrowDownRight size={17} className="text-rose-400" />)}</div>
    <p className={`mt-3 text-2xl font-semibold ${tone === 'amber' ? 'text-amber-300' : tone === 'blue' ? 'text-blue-300' : tone === 'rose' ? 'text-rose-300' : 'text-emerald-300'}`}>{value}</p>
    <p className="mt-1 text-xs text-slate-500">{detail}</p>
  </div>;
}

function TransactionPopover({ transaction, customerName, products, onClose }: { transaction: Transaction; customerName: string; products: Product[]; onClose: () => void }) {
  const itemStock = transaction.items?.map((item) => ({ ...item, stock: products.find((product) => product.id === item.product_id)?.stock ?? 0, threshold: products.find((product) => product.id === item.product_id)?.low_stock_alert ?? 5 })) ?? [];
  return <div className="absolute right-0 top-full z-30 mt-2 w-[min(380px,calc(100vw-2rem))] rounded-xl border border-slate-600 bg-slate-900 p-4 text-left shadow-2xl" role="dialog" aria-label={`Transaction ${shortId(transaction.id)} details`}>
    <div className="flex items-start justify-between gap-3 border-b border-slate-700 pb-3"><div><p className="text-xs uppercase tracking-[0.16em] text-emerald-400">Transaction detail</p><h3 className="mt-1 font-semibold text-white">{shortId(transaction.id)}</h3><p className="mt-1 text-xs text-slate-500">{new Date(transaction.created_at).toLocaleString()} · {customerName}</p></div><button onClick={onClose} className="rounded-md p-1 text-slate-400 hover:bg-slate-800 hover:text-white" aria-label="Close transaction details"><X size={16} /></button></div>
    <div className="grid grid-cols-2 gap-3 py-3 text-sm"><div><p className="text-xs text-slate-500">Total</p><p className="font-medium text-white">{currency(transaction.total_amount)}</p></div><div><p className="text-xs text-slate-500">Paid</p><p className="font-medium text-emerald-300">{currency(transaction.amount_paid)}</p></div><div><p className="text-xs text-slate-500">Payment</p><p className="capitalize text-slate-200">{transaction.payment_method.replace('_', ' ')}</p></div><div><p className="text-xs text-slate-500">Status</p><p className="capitalize text-slate-200">{transaction.status}</p></div></div>
    <div className="flex justify-end border-t border-slate-700 pt-3"><button onClick={() => window.print()} className="rounded-md border border-slate-600 px-2 py-1 text-xs text-slate-300"><FileText size={13} className="mr-1 inline" />Download transaction PDF</button></div><div className="border-t border-slate-700 pt-3"><p className="mb-2 text-xs uppercase tracking-[0.14em] text-slate-500">Items and current stock</p><div className="flex flex-col gap-2">{itemStock.map((item) => { const alert = item.stock === 0 || item.stock <= item.threshold; return <div key={item.id} className="flex items-center justify-between gap-3 rounded-lg bg-slate-800 px-3 py-2"><div className="min-w-0"><p className="truncate text-sm text-slate-200">{item.product_name}</p><p className="text-xs text-slate-500">{item.quantity} × {currency(item.unit_price)}</p></div><span className={`shrink-0 text-xs font-medium ${alert ? 'text-amber-300' : 'text-slate-400'}`}>{item.stock === 0 ? 'Out of stock' : `${item.stock} left`}</span></div>; })}</div></div>
  </div>;
}

export function ReportsWorkspace() {
  const [data, setData] = useState<ReportData>({ transactions: [], customers: [], products: [], deliveries: [], users: [] });
  const [kind, setKind] = useState<ReportKind>('sales');
  const [from, setFrom] = useState(() => new Date(Date.now() - 30 * 86400000).toISOString().slice(0, 10));
  const [to, setTo] = useState(() => new Date().toISOString().slice(0, 10));
  const [query, setQuery] = useState('');
  const [paymentMethod, setPaymentMethod] = useState('all');
  const [paymentAccount, setPaymentAccount] = useState('all');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  const refresh = async () => { setIsLoading(true); try { setData(await loadReportData()); } finally { setIsLoading(false); } };
  useEffect(() => { void refresh(); }, []);

  const transactions = useMemo(() => data.transactions.filter((tx) => tx.status !== 'voided' && inRange(tx.created_at, from, to)), [data.transactions, from, to]);
  const paymentMethods = useMemo(() => [...new Set(transactions.map((tx) => tx.payment_method))].sort(), [transactions]);
  const paymentAccounts = useMemo(() => [...new Set(transactions.map((tx) => tx.payment_account_id ? `${tx.payment_account_id}|${tx.payment_account_name ?? tx.payment_account_id}` : 'unassigned'))].sort(), [transactions]);
  const filteredTransactions = useMemo(() => transactions.filter((tx) => { const customer = data.customers.find((item) => item.id === tx.customer_id); const haystack = `${tx.id} ${customer?.name ?? 'Walk-in'} ${tx.payment_method} ${tx.payment_account_name ?? ''}`.toLowerCase(); const accountKey = tx.payment_account_id ? `${tx.payment_account_id}|${tx.payment_account_name ?? tx.payment_account_id}` : 'unassigned'; return (paymentMethod === 'all' || tx.payment_method === paymentMethod) && (paymentAccount === 'all' || accountKey === paymentAccount) && haystack.includes(query.toLowerCase()); }), [transactions, data.customers, query, paymentMethod, paymentAccount]);
  const lowStock = useMemo(() => data.products.filter((product) => product.stock === 0 || product.stock <= (product.low_stock_alert ?? 5)), [data.products]);
  const metrics = useMemo(() => {
    const gross = transactions.reduce((sum, tx) => sum + tx.total_amount, 0);
    const paid = transactions.reduce((sum, tx) => sum + tx.amount_paid, 0);
    const cost = transactions.reduce((sum, tx) => sum + (tx.items?.reduce((itemSum, item) => itemSum + item.quantity * (data.products.find((product) => product.id === item.product_id)?.cost ?? 0), 0) ?? 0), 0);
    const activeDeliveries = data.deliveries.filter((delivery) => !['delivered', 'closed', 'returned'].includes(delivery.status)).length;
    const customerIds = new Set(transactions.map((tx) => tx.customer_id).filter(Boolean));
    return { gross, paid, balance: gross - paid, cost, margin: gross - cost, activeDeliveries, customerIds: customerIds.size };
  }, [transactions, data.products, data.deliveries]);

  const inventoryValue = data.products.reduce((sum, product) => sum + product.stock * product.cost, 0);
  const reportRows = kind === 'inventory' ? data.products.filter((product) => `${product.name} ${product.sku ?? ''}`.toLowerCase().includes(query.toLowerCase())) : filteredTransactions;
  const report = REPORTS.find((item) => item.id === kind) ?? REPORTS[0];

  const exportCsv = () => { const rows = kind === 'inventory' ? data.products.map((p) => ({ product: p.name, sku: p.sku ?? '', stock: p.stock, reorder_level: p.low_stock_alert ?? 5, unit_cost: p.cost, stock_value: p.stock * p.cost })) : filteredTransactions.map((tx) => ({ transaction: tx.id, date: tx.created_at, customer: data.customers.find((c) => c.id === tx.customer_id)?.name ?? 'Walk-in', amount: tx.total_amount, paid: tx.amount_paid, payment: tx.payment_method, status: tx.status })); const headers = Object.keys(rows[0] ?? {}); const body = rows.map((row) => headers.map((header) => JSON.stringify(row[header as keyof typeof row] ?? '')).join(',')); const blob = new Blob([[headers.join(','), ...body].join('\n')], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `jimwas-${kind}-report-${from}-${to}.csv`; anchor.click(); URL.revokeObjectURL(url); };

  return <div className="flex flex-col gap-6">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.22em] text-emerald-400">Reporting center</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">Reports with the detail behind every number</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Review performance across sales, finance, inventory, delivery, customers, and users. Select a transaction to inspect its items and live stock alerts.</p></div><div className="flex gap-2"><button onClick={() => void refresh()} disabled={isLoading} className="inline-flex items-center gap-2 rounded-lg border border-slate-600 px-3 py-2 text-sm text-slate-200 hover:bg-slate-800 disabled:opacity-50"><RefreshCw size={16} className={isLoading ? 'animate-spin' : ''} /> Refresh</button>{kind !== 'august-sales' && (<><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-lg border border-slate-600 px-3 py-2 text-sm text-slate-200 hover:bg-slate-800"><FileText size={16} /> Download PDF</button><button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-3 py-2 text-sm font-medium text-white hover:bg-emerald-500"><Download size={16} /> Export CSV</button></>)}</div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{REPORTS.map(({ id, label, description, icon: Icon }) => <button key={id} onClick={() => { setKind(id); setSelectedId(null); }} className={`flex items-start gap-3 rounded-xl border p-4 text-left transition ${kind === id ? 'border-emerald-500/70 bg-emerald-950/30' : 'border-slate-700 bg-slate-800/60 hover:border-slate-500'}`}><span className={`rounded-lg p-2 ${kind === id ? 'bg-emerald-500/20 text-emerald-300' : 'bg-slate-700 text-slate-300'}`}><Icon size={18} /></span><span><span className="block font-medium text-white">{label}</span><span className="mt-1 block text-xs leading-5 text-slate-400">{description}</span></span></button>)}</div>
    {kind === 'august-sales' ? (
      <AugustSalesReportView />
    ) : (
      <>
        <div className="flex flex-col gap-3 rounded-xl border border-slate-700 bg-slate-800/70 p-4 lg:flex-row lg:items-end lg:justify-between"><div className="flex flex-wrap gap-3"><label className="text-xs text-slate-400">From<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="mt-1 block rounded-lg border border-slate-600 bg-slate-900 px-3 py-2 text-sm text-white" /></label><label className="text-xs text-slate-400">To<input type="date" value={to} onChange={(event) => setTo(event.target.value)} className="mt-1 block rounded-lg border border-slate-600 bg-slate-900 px-3 py-2 text-sm text-white" /></label></div><label className="text-xs text-slate-400">Payment method<select value={paymentMethod} onChange={(event) => setPaymentMethod(event.target.value)} className="mt-1 block rounded-lg border border-slate-600 bg-slate-900 px-3 py-2 text-sm text-white"><option value="all">All methods</option>{paymentMethods.map((method) => <option key={method} value={method}>{method.replace('_', ' ')}</option>)}</select></label><label className="text-xs text-slate-400">Payment account<select value={paymentAccount} onChange={(event) => setPaymentAccount(event.target.value)} className="mt-1 block max-w-56 rounded-lg border border-slate-600 bg-slate-900 px-3 py-2 text-sm text-white"><option value="all">All accounts</option>{paymentAccounts.map((account) => <option key={account} value={account}>{account === 'unassigned' ? 'Unassigned' : account.split('|')[1]}</option>)}</select></label><label className="relative min-w-64 text-xs text-slate-400"><span className="sr-only">Search report</span><Search size={16} className="absolute left-3 top-9 text-slate-500" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${report.label.toLowerCase()} report`} className="w-full rounded-lg border border-slate-600 bg-slate-900 py-2 pl-9 pr-3 text-sm text-white placeholder:text-slate-600" /></label></div>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label={kind === 'inventory' ? 'Stock value' : 'Gross value'} value={currency(kind === 'inventory' ? inventoryValue : metrics.gross)} detail={kind === 'inventory' ? `${data.products.length} catalog items` : `${transactions.length} transactions in range`} /><Metric label={kind === 'financial' ? 'Outstanding' : 'Collected'} value={currency(kind === 'financial' ? metrics.balance : metrics.paid)} detail={kind === 'financial' ? 'Unpaid or installment balance' : 'Amount recorded as paid'} tone={kind === 'financial' ? 'amber' : 'emerald'} /><Metric label={kind === 'delivery' ? 'In fulfillment' : kind === 'customer' ? 'Active customers' : 'Average basket'} value={kind === 'delivery' ? `${metrics.activeDeliveries}` : kind === 'customer' ? `${metrics.customerIds}` : currency(transactions.length ? metrics.gross / transactions.length : 0)} detail={kind === 'delivery' ? 'Open outbound deliveries' : kind === 'customer' ? 'Unique buyers in period' : 'Gross sales per transaction'} tone="blue" /><Metric label={kind === 'inventory' ? 'Stock alerts' : kind === 'user' ? 'Users' : 'Margin signal'} value={kind === 'inventory' ? `${lowStock.length}` : kind === 'user' ? `${data.users.length}` : currency(metrics.margin)} detail={kind === 'inventory' ? 'At or below reorder level' : kind === 'user' ? 'Configured staff accounts' : 'Gross less known product cost'} tone={kind === 'inventory' && lowStock.length ? 'rose' : 'amber'} trend={kind === 'inventory' && lowStock.length ? 'down' : 'up'} /></div>
        <div className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><section className="min-w-0 rounded-xl border border-slate-700 bg-slate-800/70"><div className="flex items-center justify-between gap-3 border-b border-slate-700 p-4"><div><h2 className="font-semibold text-white">{report.label} detail</h2><p className="mt-1 text-xs text-slate-500">{kind === 'inventory' ? `${reportRows.length} products` : `${reportRows.length} transactions`} · {from} to {to}</p></div><FileText size={18} className="text-slate-500" /></div>{kind === 'inventory' ? <div className="divide-y divide-slate-700">{(reportRows as Product[]).slice(0, 20).map((product) => { const alert = product.stock === 0 || product.stock <= (product.low_stock_alert ?? 5); return <div key={product.id} className="flex items-center justify-between gap-4 p-4"><div className="min-w-0"><p className="truncate text-sm font-medium text-white">{product.name}</p><p className="mt-1 text-xs text-slate-500">{product.sku || 'No SKU'} · {product.category || 'Uncategorised'}</p></div><div className="text-right"><p className={`text-sm font-medium ${alert ? 'text-amber-300' : 'text-slate-200'}`}>{product.stock} units</p><p className="text-xs text-slate-500">{currency(product.stock * product.cost)}</p></div></div>; })}</div> : <div className="divide-y divide-slate-700">{(reportRows as Transaction[]).slice(0, 12).map((tx) => { const customerName = data.customers.find((c) => c.id === tx.customer_id)?.name ?? 'Walk-in customer'; return <div key={tx.id} className="relative flex items-center justify-between gap-4 p-4 hover:bg-slate-800"><button onClick={() => setSelectedId(selectedId === tx.id ? null : tx.id)} className="min-w-0 flex-1 text-left"><p className="truncate text-sm font-medium text-white">{customerName}</p><p className="mt-1 text-xs text-slate-500">{shortId(tx.id)} · {new Date(tx.created_at).toLocaleString()} · {tx.items?.length ?? 0} items</p></button><div className="shrink-0 text-right"><p className="text-sm font-medium text-emerald-300">{currency(tx.total_amount)}</p><p className="mt-1 text-xs capitalize text-slate-500">{tx.payment_method.replace('_', ' ')}</p></div>{selectedId === tx.id && <TransactionPopover transaction={tx} customerName={customerName} products={data.products} onClose={() => setSelectedId(null)} />}</div>; })}</div>}{!reportRows.length && <div className="p-10 text-center text-sm text-slate-500">No records match this report and date range.</div>}</section>
        <aside className="flex flex-col gap-4"><div className="rounded-xl border border-amber-700/50 bg-amber-950/20 p-4"><div className="flex items-start gap-3"><AlertTriangle size={19} className="mt-0.5 shrink-0 text-amber-300" /><div><h2 className="font-medium text-amber-200">Stock level alerts</h2><p className="mt-1 text-xs leading-5 text-amber-100/60">These alerts are also surfaced inside transaction detail so teams can act before the next sale.</p></div></div><div className="mt-4 flex flex-col gap-2">{lowStock.slice(0, 6).map((product) => <div key={product.id} className="flex items-center justify-between gap-3 rounded-lg bg-slate-900/60 px-3 py-2"><span className="truncate text-sm text-slate-200">{product.name}</span><span className={`shrink-0 text-xs font-medium ${product.stock === 0 ? 'text-rose-300' : 'text-amber-300'}`}>{product.stock === 0 ? 'Out' : `${product.stock} left`}</span></div>)}{!lowStock.length && <p className="text-sm text-emerald-300">All products are above their reorder levels.</p>}</div></div><div className="rounded-xl border border-slate-700 bg-slate-800/70 p-4"><div className="flex items-center justify-between"><h2 className="font-medium text-white">Payment mix</h2><ChevronDown size={16} className="text-slate-500" /></div><div className="mt-4 flex flex-col gap-3">{Object.entries(transactions.reduce<Record<string, number>>((mix, tx) => { mix[tx.payment_method] = (mix[tx.payment_method] ?? 0) + tx.total_amount; return mix; }, {})).sort(([, a], [, b]) => b - a).slice(0, 5).map(([method, amount]) => <div key={method}><div className="flex justify-between text-xs"><span className="capitalize text-slate-400">{method.replace('_', ' ')}</span><span className="text-slate-200">{currency(amount)}</span></div><div className="mt-1 h-1.5 rounded-full bg-slate-700"><div className="h-1.5 rounded-full bg-emerald-500" style={{ width: `${metrics.gross ? Math.min(100, amount / metrics.gross * 100) : 0}%` }} /></div></div>)}{!transactions.length && <p className="text-sm text-slate-500">No payment activity in this range.</p>}</div></div></aside></div>
      </>
    )}
  </div>;
}
